### ISSUE TITLE
报错太多

### ISSUE THREAD

**Issue by dbfterrific** [supnate/react-geek-time#10]
项目跑起来貌似全是报错，没有一个菜单点开， 里面的项目是能成功运行的😅😅

**Comment by dbfterrific** [comment]
> 项目跑起来貌似全是报错，没有一个菜单点开， 里面的项目是能成功运行的😅😅

eg：
![image](https://user-images.githubusercontent.com/20207490/55704690-6494e680-5a0f-11e9-992f-dc457c7f8785.png)

**Comment by supnate** [comment]
谢谢报告，贴图的错误是 warning，不影响功能。你是本地运行吗，左边菜单点上去出什么错？
你可以访问在线的演示：https://codesandbox.io/s/github/supnate/react-geek-time
确认过是都可以运行的，在线演示也可以直接修改代码看效果。

**Comment by supnate** [comment]
Warning 的问题我会修复。
